name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            conan-target: default
          - os: ubuntu-latest
            conan-target: release
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Conan
        run: pip install conan==2.*

      - name: Cache Conan dependencies
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ${{ runner.os == 'windows-latest' && 'C:\\Users\\runneradmin\\.conan2' || '/home/runner/.conan2' }}
          key: conan-${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}
          
      - name: Create default profile (if cache miss)
        if: steps.cache-conan.outputs.cache-hit != 'true'
        run: conan profile detect --force

      - name: Install deps (Conan)
        run: conan install . --output-folder build --build=missing

      - name: Configure CMake
        run: cmake --preset conan-${{ matrix.conan-target }}

      - name: Build
        run: cmake --build build --config Release

      - name: Run unit tests
        run: ctest --output-on-failure -C Release
        working-directory: build
